# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7457a2a973e162afc872aae2f049e1293426f5693d32954c9eab0dc4550764592026d3281bd87fe5b4d5b1b2a27b0734c54cd039b190334a26652b2169192945

test:
  secret_key_base: 0c4244327faa700f9b56a5ebfb151dd8b4e59b14b50cda4595cc7acd83c5567828dc59bbcadaca64a8a39ef9b3fce26bc0dfc259a3994f9f4403f4ca3e4bd591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
